const inventory = [
  {
    id: 1,
    name: "Industrial Drill Press",
    category: "Machinery",
    supplier: "Apex Supply",
    price: 420.0,
    stock: 12,
  },
  {
    id: 2,
    name: "LED Safety Vest",
    category: "Safety",
    supplier: "Ridge Safety",
    price: 19.99,
    stock: 220,
  },
  {
    id: 3,
    name: "Ergonomic Office Chair",
    category: "Office",
    supplier: "DeskDirect",
    price: 145.5,
    stock: 34,
  },
  {
    id: 4,
    name: "Bluetooth Headset",
    category: "Electronics",
    supplier: "Vista Tech",
    price: 84.99,
    stock: 58,
  },
  {
    id: 5,
    name: "Canvas Work Gloves",
    category: "Safety",
    supplier: "StrongHand",
    price: 9.5,
    stock: 140,
  },
  {
    id: 6,
    name: "Cardboard Shipping Boxes",
    category: "Packaging",
    supplier: "PackWell",
    price: 28.75,
    stock: 68,
  },
  {
    id: 7,
    name: "Wireless Mouse",
    category: "Electronics",
    supplier: "Pulse Gear",
    price: 22.5,
    stock: 93,
  },
  {
    id: 8,
    name: "Worksite Hammer",
    category: "Tools",
    supplier: "BuildRight",
    price: 32.0,
    stock: 50,
  },
  {
    id: 9,
    name: "Thermal Label Printer",
    category: "Office",
    supplier: "LabelLab",
    price: 195.0,
    stock: 16,
  },
  {
    id: 10,
    name: "Stainless Steel Shelving",
    category: "Machinery",
    supplier: "MetalMax",
    price: 299.99,
    stock: 8,
  },
  {
    id: 11,
    name: "Performance Polo Shirt",
    category: "Apparel",
    supplier: "UniformCo",
    price: 14.99,
    stock: 132,
  },
  {
    id: 12,
    name: "Heavy-Duty Extension Cord",
    category: "Tools",
    supplier: "PowerEdge",
    price: 27.0,
    stock: 76,
  },
];

export default inventory;
